- pipeline.id: http-apache-access
  pipeline.batch.size: 5
  path.config: "/usr/share/logstash/pipeline/http-apache/access_logs.conf"
- pipeline.id: http-apache-errors
  pipeline.batch.size: 1
  path.config: "/usr/share/logstash/pipeline/http-apache/error_logs.conf"
- pipeline.id: http-json-only
  path.config: "/usr/share/logstash/pipeline/http-json-only"

